### ISSUE TITLE
[DOC]: Adidionar a ata do ciclo 5 na aba de ciclos da documentação

### ISSUE THREAD

**Issue by DanielRogs** [mdsreq-fga-unb/2024.1-RISO-#42]
### Descreva o que deve ser feito nesta seção da documentação.

Os responsáveis deverão escrever a ata de reunião na documentação do projeto descrevendo os entregáveis da semana, as atividades em débito e as novas atividades atribuídas. além dos participantes presentes e o horário da reunião.

**Comment by xGabrielCv** [comment]
ata 5 adicionada
