### ISSUE TITLE
REFATORAR FRONT-END | INTERFACE

### ISSUE THREAD

**Issue by DanielRogs** [mdsreq-fga-unb/2024.1-RISO-#48]
### Task a ser executada.

A utilização incorreta do CSS pura na aplicação em React.js desencadeou interferências na estilização em toda as páginas, quebrando-as. Será necessário refazer o frontend do zero, dessa vez, utilizando a biblioteca STYLED-COMPONENTS, ou método semelhante para corrigir os problemas de vazamento de estilização entre páginas.

### Quais são as Definition´s of Done (DoD) da atividade?

- [x] O códico possui 100% de utilização da biblioteca styled-components;
- [x] 0% de configuração de estilo são vazados para as outras páginas.

**Comment by xGabrielCv** [comment]
Refatoração concluída
