### ISSUE TITLE
Visão geral do Projeto

### ISSUE THREAD

**Issue by phmelosilva** [mdsreq-fga-unb/2024.1-RISO-#51]
## Planejamento das fases do Projeto

- [x] Falta definir a data de entrega do produto no planejamento das fases de projeto.
- [x] A partir do ciclo 6, as datas são consideradas a partir de 2023 e não 2024.

![Captura de tela 2024-08-30 100934](https://github.com/user-attachments/assets/4309e65f-7c7b-409c-b718-d624a91f8db1)

## Gerenciamento de Riscos

- [x] Faltou uma melhor explicação sobre a variável probabilidade e sua ocorrência, o que define uma probabilidade baixa, média, etc?
- [x] Há uma documentação do gerenciamento de riscos em cada ciclo, o que é bem legal, mas há uma falta de atualização desse histórico de riscos com os ciclos mais atuais.

## Critérios de Replanejamento

- [x] Distribuição e explicação condizente dos históricos de riscos quanto ao replanejamento adotado pelo grupo, mas há apenas registro do ciclo 1 até o ciclo 4.

### Quais são as Definition´s of Done (DoD) da atividade?

- [x] Correção e aprimoramento do artefato em relação ao que foi indicado na descrição;

**Comment by xGabrielCv** [comment]
As datas foram corrigidas, e o gerenciamento de riscos foi atualizado.
