### ISSUE TITLE
Processo de Desenvolvimento de Software

### ISSUE THREAD

**Issue by phmelosilva** [mdsreq-fga-unb/2024.1-RISO-#52]
## Metodologia

- [x] Há um uso condizente do Modelo Gupta para a escolha do processo de desenvolvimento, porém no texto há uma citação de que o método ágil XP é uma abordagem dirigida a plano, sendo que essa abordagem é ágil, isso precisa ser corrigido.

## Processos e Procedimentos

- [x] Verificação e Validação está como atividade de software, e não de engenharia de requisitos ao incluir testes de software, busquem separar isso.
- [x] Há presente outras atividades que extrapolam a Engenharia de Requisitos, como usabilidade e implementação, poderiam ser citadas a parte das atividades de Engenharia de Requisitos.
- [x] O tópico de estrutura analítica do projeto não apresenta explicação sobre o uso da estrutura, o que confunde o entendimento sobre esse conteúdo e o seu propósito neste tópico do artefato.

### Quais são as Definition´s of Done (DoD) da atividade?

- [x] Correção e aprimoramento do artefato em relação ao que foi indicado na descrição;

**Comment by xGabrielCv** [comment]
processo de desenvolvimento de software atualizado
