### ISSUE TITLE
Planejamento dos Ciclos

### ISSUE THREAD

**Issue by phmelosilva** [mdsreq-fga-unb/2024.1-RISO-#53]
- [x] O grupo não atualizou o planejamento dos ciclos com as datas atuais e não está coerente com o planejamento das fases do projeto apresentado no artefato “Visão Geral do Projeto”. Busquem atualizar os ciclos e os seus registros o quanto antes!

**Comment by xGabrielCv** [comment]
Ciclos atualizados ate o 7 em dia com a data atual
