### ISSUE TITLE
PBB

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2024.1-RISO-#55]
### Descreva o que deve ser feito nesta seção da documentação.

- a estrutura está correta e consistente
- o quadro de features está incompleto
- alguns PBIs não me parecem consistentes. Exemplo:
![image](https://github.com/user-attachments/assets/f14d33b9-7660-40f9-a5ab-73bdf9391c70)
![image](https://github.com/user-attachments/assets/5611debe-137f-4229-8b82-c1c150a19baf)

**Comment by xGabrielCv** [comment]
corrigido
