### ISSUE TITLE
USM

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2024.1-RISO-#57]
### Descreva o que deve ser feito nesta seção da documentação.

- A estrutura está correta.
- O conteúdo, está incorreto, em um nível de granularidade muito baixo. E, quando chega nas US, está em um nível de campo. Cada US a inserção de um campo. Não faz sentido. Todo o mapa precisa de revisão. O problema está no nível de granularidade das atividades. a partir delas, deve-se ajustar as US.

- Exemplo:
![image](https://github.com/user-attachments/assets/14037df7-8b62-44d0-be6b-b37085b12588)
![image](https://github.com/user-attachments/assets/3b298d85-1ce6-495e-9d8a-cbb84975c586)

**Comment by xGabrielCv** [comment]
USM corrigida
